GET http://localhost:4000/posts/ HTTP/1.1

GET http://localhost:4000/posts/6 HTTP/1.1

POST http://localhost:4000/posts HTTP/1.1
content-type: application/json

{
    "content": "sixth post to be published"
}

DELETE http://localhost:4000/posts/7 HTTP/1.1